#!/usr/bin/env python3
import sys
print("Ejecutando validación personalizada...")
print("Falla intencional...")
sys.exit(1)  # 0 para éxito, otro valor para fallo
